// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Amro Deek"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticate user via Keycloak and return access \u0026 refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoke current session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Refresh payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refresh access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "Refresh payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/student/activate": {
            "get": {
                "description": "Check activation link validity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify activation token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Activation token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/student/complete": {
            "post": {
                "description": "Finalize student account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Complete registration",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompleteStudentRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/student/request-activation": {
            "post": {
                "description": "Send activation email to university address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Request activation link",
                "parameters": [
                    {
                        "description": "Email",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestActivationRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/student/resend": {
            "post": {
                "description": "Resend activation email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Resend activation link",
                "parameters": [
                    {
                        "description": "Email",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResendActivationRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/student/status": {
            "get": {
                "description": "Check if student email is verified and registration can be completed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get registration status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StudentRegistrationStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/categories": {
            "get": {
                "description": "Returns all marketplace categories for dropdown selection. Public endpoint, no auth required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metadata"
                ],
                "summary": "List Categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Category"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/items": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mints a new item for sale. Enforces 5 listings per day limit (NFR-1).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Create Item Listing",
                "parameters": [
                    {
                        "description": "Listing Details",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateItemCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Item"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/items/feed": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns available items scoped automatically to the authenticated user's university. Newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get Marketplace Feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Items per page (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Full-text search on title",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category UUID",
                        "name": "category_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.FeedItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/items/my": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all items owned by the currently authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get My Listings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Items per page (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.FeedItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/items/picture/upload-url": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a pre-signed S3 URL for uploading item images.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Generate Item Image Upload URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MIME type (e.g. image/jpeg)",
                        "name": "content_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/items/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the full listing including attachments.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get Item Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ItemDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes a listing. Only the owner can delete. Preserves transaction history.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Delete Item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/items/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transitions an item status (AVAILABLE → RESERVED → SOLD). Only the owner can update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Update Item Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status payload",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Primary entry point for mobile apps. Returns aggregated user info, student data, and the unique ` + "`" + `profile_id` + "`" + ` required for all social/follow actions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "[Self] Get My Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProfileDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates social identity fields like display name, bio, and finishing the S3 profile picture upload sync.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "[Self] Update Base Profile",
                "parameters": [
                    {
                        "description": "Profile Update Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.UpdateProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/profile/picture/upload-url": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "📱 **FLUTTER INTEGRATION WORKFLOW (3 STEPS):**\\n\\n**Step 1 (The Secure Handshake):** Call this endpoint with ` + "`" + `{\"filename\": \"pic.png\", \"content_type\": \"image/png\"}` + "`" + ` to secure a ticket. It returns an ` + "`" + `upload_url` + "`" + ` and an ` + "`" + `object_key` + "`" + `. Note: Ensure you store your ` + "`" + `profile_id` + "`" + ` returned from ` + "`" + `GET /api/v1/profile` + "`" + ` for all future social interactions.\\n\\n**Step 2 (The Direct Upload):** Bypass this backend entirely and upload your binary image file directly to AWS S3. Perform an HTTP ` + "`" + `PUT` + "`" + ` request targeting the ` + "`" + `upload_url` + "`" + ` you received. You MUST attach the exact same ` + "`" + `Content-Type` + "`" + ` header (e.g. ` + "`" + `image/png` + "`" + `) to the ` + "`" + `PUT` + "`" + ` request. Do not send ` + "`" + `FormData` + "`" + `, send raw binary data.\\n\\n**Step 3 (Final Sync):** Once AWS gives you a ` + "`" + `200 OK` + "`" + `, call ` + "`" + `PUT /api/v1/profile` + "`" + ` and set ` + "`" + `\"profile_picture_url\"` + "`" + ` to the ` + "`" + `object_key` + "`" + ` that was returned in Step 1. Your updated profile is now ready to be discovered via the public profile lookup.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Generate S3 Upload URL",
                "parameters": [
                    {
                        "description": "File Info",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.GenerateUploadURLReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/profile/student": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Specifically for student-only data. Updates the ` + "`" + `major` + "`" + ` and ` + "`" + `academic_year` + "`" + `. This is decoupled from the base profile to separate academic status from social identity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "[Self] Update Academic Info",
                "parameters": [
                    {
                        "description": "Student Update Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.UpdateStudentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns authenticated user profile -test",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{profileId}/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch public-facing info of any user (display name, bio, counters). Use this to render the profile page of others before a follow action.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Social"
                ],
                "summary": "[Public] Discover User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "profileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProfileDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{userId}/profile-by-user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch the public profile of an item owner using their user ID (the owner_id field returned in the feed). Use this when clicking on an item to show the seller's profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Social"
                ],
                "summary": "[Public] Get Owner Profile by User ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (owner_id from the item feed)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProfileDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorFrame"
                        }
                    }
                }
            }
        },
        "/purchases/items/{itemId}/request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new purchase request from the authenticated user to buy a specific item",
                "tags": [
                    "Purchases"
                ],
                "summary": "Send a purchase request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PurchaseRequest"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/purchases/items/{itemId}/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all purchase requests made for a specific item",
                "tags": [
                    "Purchases"
                ],
                "summary": "List purchase requests for an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PurchaseRequest"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queue/{itemId}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds the authenticated user to the giveaway queue for the specified item",
                "tags": [
                    "Giveaway Queue"
                ],
                "summary": "Join an item's giveaway queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.QueueEntry"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queue/{itemId}/leave": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes the authenticated user from the giveaway queue for the specified item",
                "tags": [
                    "Giveaway Queue"
                ],
                "summary": "Leave an item's giveaway queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queue/{itemId}/position/{entryId}": {
            "get": {
                "description": "Retrieves the current numerical position of a specific queue entry for an item",
                "tags": [
                    "Giveaway Queue"
                ],
                "summary": "Get user position in queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Queue Entry ID",
                        "name": "entryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns { \\\"position\\\": 1 }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transactions/{transactionId}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows the seller to confirm a transaction",
                "tags": [
                    "Transactions"
                ],
                "summary": "Confirm a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "transactionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns { \\\"message\\\": \\\"Confirmed\\\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{profileId}/follow": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticated user follows the profile with the given profileId",
                "tags": [
                    "Social"
                ],
                "summary": "Follow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target profile ID",
                        "name": "profileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "cannot follow yourself",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{profileId}/followers": {
            "get": {
                "description": "Returns all profiles following the given profileId",
                "tags": [
                    "Social"
                ],
                "summary": "Get followers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "profileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Follow"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{profileId}/following": {
            "get": {
                "description": "Returns all profiles that the given profileId follows",
                "tags": [
                    "Social"
                ],
                "summary": "Get following",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "profileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Follow"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{profileId}/is-following": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns whether the authenticated user follows the given profile",
                "tags": [
                    "Social"
                ],
                "summary": "Check follow status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target profile ID",
                        "name": "profileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns { \\\"is_following\\\": boolean }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{profileId}/unfollow": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticated user unfollows the profile with the given profileId",
                "tags": [
                    "Social"
                ],
                "summary": "Unfollow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target profile ID",
                        "name": "profileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Attachment": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "uploaded_at": {
                    "type": "string"
                }
            }
        },
        "domain.Category": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.CreateItemCommand": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "object_keys": {
                    "description": "S3 keys pointing to uploaded images",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "owner_id": {
                    "type": "string"
                },
                "pickup_location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.FeedItem": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "owner_display_name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "owner_profile_pic_url": {
                    "type": "string"
                },
                "pickup_location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/domain.ItemStatus"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.Follow": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "followedAt": {
                    "type": "string"
                },
                "followerProfileID": {
                    "type": "string"
                },
                "followingProfileID": {
                    "type": "string"
                },
                "profilePictureURL": {
                    "type": "string"
                }
            }
        },
        "domain.Item": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "pickup_location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/domain.ItemStatus"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.ItemDetail": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Attachment"
                    }
                },
                "category_id": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "owner_display_name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "owner_profile_pic_url": {
                    "type": "string"
                },
                "pickup_location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/domain.ItemStatus"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.ItemStatus": {
            "type": "string",
            "enum": [
                "AVAILABLE",
                "RESERVED",
                "SOLD"
            ],
            "x-enum-varnames": [
                "ItemStatusAvailable",
                "ItemStatusReserved",
                "ItemStatusSold"
            ]
        },
        "domain.PurchaseRequest": {
            "type": "object",
            "properties": {
                "buyerID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "itemID": {
                    "type": "string"
                },
                "requestID": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.PurchaseRequestStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.PurchaseRequestStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "FROZEN",
                "CANCELLED"
            ],
            "x-enum-varnames": [
                "PurchaseRequestPending",
                "PurchaseRequestAccepted",
                "PurchaseRequestRejected",
                "PurchaseRequestFrozen",
                "PurchaseRequestCancelled"
            ]
        },
        "domain.QueueEntry": {
            "type": "object",
            "properties": {
                "entryID": {
                    "type": "string"
                },
                "entryStatus": {
                    "$ref": "#/definitions/domain.QueueEntryStatus"
                },
                "itemID": {
                    "type": "string"
                },
                "joinedAt": {
                    "type": "string"
                },
                "turnStartedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "domain.QueueEntryStatus": {
            "type": "string",
            "enum": [
                "WAITING",
                "RESERVED",
                "EXPIRED",
                "COMPLETED",
                "CANCELLED"
            ],
            "x-enum-varnames": [
                "QueueStatusWaiting",
                "QueueStatusReserved",
                "QueueStatusExpired",
                "QueueStatusCompleted",
                "QueueStatusCancelled"
            ]
        },
        "dto.CompleteStudentRegistrationRequest": {
            "type": "object",
            "properties": {
                "academicYear": {
                    "type": "integer"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.LoginUser"
                }
            }
        },
        "dto.LoginUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.MeResponse": {
            "description": "Current authenticated user",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@bzu.edu"
                },
                "id": {
                    "type": "string",
                    "example": "b3c2f9a1"
                },
                "role": {
                    "type": "string",
                    "example": "STUDENT"
                }
            }
        },
        "dto.RefreshRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "dto.RefreshResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "dto.RequestActivationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ResendActivationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.StudentRegistrationStatusResponse": {
            "type": "object",
            "properties": {
                "can_complete_registration": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "is_used": {
                    "type": "boolean"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "verified_at": {
                    "type": "string"
                }
            }
        },
        "middleware.ErrCode": {
            "type": "string",
            "enum": [
                "USER_NOT_FOUND",
                "EMAIL_ALREADY_USED",
                "INVALID_CREDENTIALS",
                "ACCOUNT_SUSPENDED",
                "EMAIL_NOT_VERIFIED",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "TOKEN_INVALID",
                "TOKEN_EXPIRED",
                "LISTING_NOT_FOUND",
                "LISTING_CLOSED",
                "LISTING_LIMIT_REACHED",
                "ALREADY_REVIEWED",
                "REVIEW_NOT_ALLOWED",
                "VALIDATION_FAILED",
                "INVALID_INPUT",
                "CONFLICT",
                "RATE_LIMITED",
                "DATABASE_ERROR",
                "INTERNAL_ERROR"
            ],
            "x-enum-varnames": [
                "CodeUserNotFound",
                "CodeEmailAlreadyUsed",
                "CodeInvalidCredentials",
                "CodeAccountSuspended",
                "CodeEmailNotVerified",
                "CodeUnauthorized",
                "CodeForbidden",
                "CodeTokenInvalid",
                "CodeTokenExpired",
                "CodeListingNotFound",
                "CodeListingClosed",
                "CodeListingLimitReached",
                "CodeAlreadyReviewed",
                "CodeReviewNotAllowed",
                "CodeValidationFailed",
                "CodeInvalidInput",
                "CodeConflict",
                "CodeRateLimited",
                "CodeDatabaseError",
                "CodeInternalError"
            ]
        },
        "middleware.ErrorFrame": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/middleware.ErrCode"
                },
                "correlationId": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "retryable": {
                    "type": "boolean"
                },
                "statusCode": {
                    "type": "integer"
                },
                "ts": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "profile.GenerateUploadURLReq": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            }
        },
        "profile.UpdateProfileReq": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "profile_picture_url": {
                    "type": "string"
                }
            }
        },
        "profile.UpdateStudentReq": {
            "type": "object",
            "properties": {
                "academic_year": {
                    "type": "integer"
                },
                "major": {
                    "type": "string"
                }
            }
        },
        "services.ProfileDTO": {
            "type": "object",
            "properties": {
                "academic_year": {
                    "type": "integer"
                },
                "bio": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "display_name_last_changed_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "follower_count": {
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "major": {
                    "description": "Student specific",
                    "type": "string"
                },
                "profile_id": {
                    "type": "string"
                },
                "profile_picture_url": {
                    "type": "string"
                },
                "rating_count": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "sold_items_count": {
                    "type": "integer"
                },
                "student_id": {
                    "type": "string"
                },
                "total_reviews_count": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Dealna API",
	Description:      "Dealna backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
